### ISSUE TITLE
请问之前版本的easytorch中的/core/runner.py中的to_running_device函数现在改成什么名字了，谢谢

### ISSUE THREAD

**Issue by MysteryNull** [cnstark/easytorch#83]
请问之前版本的easytorch中的/core/runner.py中的to_running_device函数现在改成什么名字了，谢谢

**Comment by cnstark** [comment]
请参考https://github.com/cnstark/easytorch/blob/master/examples/imagenet/imagenet_runner.py#L9
新版本新增了device模块，之前的self.to_running_device改为device模块中的to_device

**Comment by MysteryNull** [comment]
感谢回复
